# Ansible Galaxy requirements file for Windows and VMware automation

# Windows support collections
- name: ansible.windows
  version: ">=1.14.0"
  description: "Core Windows modules for managing Windows hosts"

- name: community.windows
  version: ">=1.13.0"
  description: "Additional Windows modules contributed by the community"

- name: microsoft.ad
  version: ">=1.3.0"
  description: "Active Directory management"

# VMware support collections
- name: community.vmware
  version: ">=3.6.0"
  description: "VMware modules for managing vSphere environments"

- name: vmware.vmware_rest
  version: ">=2.3.0"
  description: "VMware REST API modules"

# WinRM support
- name: chocolatey.chocolatey
  version: ">=1.4.0"
  description: "Chocolatey package manager integration"

# Additional support collections
- name: community.general
  version: ">=6.6.0"
  description: "General purpose modules and plugins"

# Dependencies for handling Windows credentials
- name: ansible.netcommon
  version: ">=5.1.1"
  description: "Common network modules for credential management"
