- hosts: all
  become: true
  tasks:
    - name: Update the repository cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes
