name: semaphore-gui-roles
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - pyqt=5.15.7  # Main GUI framework
  - pytest>=7.0.0  # Testing framework
  - flake8>=4.0.1  # Code quality
  - black>=22.3.0  # Code formatting
  - pyyaml>=6.0  # YAML parsing and generation
  - numpy>=1.22.0  # Numerical operations
  - pandas>=1.4.0  # Data manipulation for role metadata
  - matplotlib>=3.5.0  # Visualization for role metrics
  - networkx>=2.8.0  # Graph visualization for role relationships
  - sqlalchemy>=1.4.0  # Database ORM for role storage
  - cryptography>=37.0.0  # Security for role-based access control
  - setuptools>=60.0.0
  - pip:
    - semaphore-core>=1.0.0  # Core Semaphore library
    - qtawesome>=1.1.0  # Icons for the GUI
    - pyqtgraph>=0.12.0  # Interactive graphs
    - jsonschema>=4.0.0  # Role schema validation
    - pydantic>=1.9.0  # Data validation for role models
    - typer>=0.4.0  # CLI interface
    - rich>=11.0.0  # Rich terminal output
    - watchdog>=2.1.0  # File system monitoring for role updates
    - ldap3>=2.9.0  # LDAP integration for role synchronization
    - jwt>=1.3.0  # JWT for role authentication tokens
    - rbac>=0.2.0  # Role-based access control helpers
    - marshmallow>=3.15.0  # Object serialization/deserialization
    - python-jose>=3.3.0  # More comprehensive JWT implementation
    - fastapi>=0.85.0  # API framework for role service integration
